### ISSUE TITLE
BlurView doesn't work on iOS9 anymore

### ISSUE THREAD

**Issue by olivierlesnicki** [Kureev/react-native-blur#23] opened 2015-09-18 20:56 UTC
Works fine on iOS8, displays solid background (no blur effect) on iOS9

**Comment by olivierlesnicki** [comment] 2015-09-19 10:00
Seem I can make it work if I specify a backgroundColor in the style.

**Comment by Kureev** [comment] 2015-09-20 11:32
Can you tell us more about it? Maybe it's worth to add to README

**Comment by alvaromb** [comment] 2015-09-23 16:25
It's working perfectly here under iOS 9. Must be something with your code, if you post it maybe we could help.

<img width="578" alt="screen shot 2015-09-23 at 18 24 38" src="https://cloud.githubusercontent.com/assets/289640/10051166/75f19544-6220-11e5-9a35-2ca2f0c2e8b6.png">

**Comment by alvaromb** [comment] 2015-09-25 14:26
@olivierlesnicki  I've just experienced this error in all platforms due to setting a ``backgroundColor`` prop in the parent ``<ListView />`` component that wraps the cell that has the ``<BlurView />``. It might be due how React Native blends views when rendering, IDK.

@Kureev if you want I can put an example reproducing this issue this weekend.

**Comment by alvaromb** [comment] 2015-09-25 14:26
Here's an screenshot with the issue
<img width="465" alt="screen shot 2015-09-25 at 16 26 23" src="https://cloud.githubusercontent.com/assets/289640/10103052/3958b33c-63a2-11e5-85ce-5798a7e28e8a.png">

**Comment by Kureev** [comment] 2015-09-26 22:37
Yeah, it's definitely about the RN itself. I think that example is not needed if @olivierlesnicki can confirm that he experience exactly this issue (in this case I don't have that much ideas how to fix it either remove background color property from the parent <ListView />).

@brentvatne mb you have any ideas? Otherwise I gonna close it.

**Comment by olivierlesnicki** [comment] 2015-09-27 06:51
@Kureev hard to replicate. In my case I have a large number of nested views, and I'm unable to extract the combination that is causing the issue. But I'm not using ListViews

**Comment by alvaromb** [comment] 2015-09-27 06:55
Probably is not an issue with ListView but with how RN renders the view tree. It must be blending views to improve performance so the blurred view gets squashed into another super view. 

Enviado desde mi iPhone

**Comment by Kureev** [comment] 2015-10-05 22:23
So, any updates so far?

**Comment by holmesal** [comment] 2015-10-06 17:27
I had this problem as well:
```html
<App>    <--- backgroundColor: 'something-solid'
  (many nested components)
    <BlurView>    <--- incorrectly has solid background
```

Setting 

```javascript
backgroundColor: 'transparent'
``` 

on the (immediate) parent of `<BlurView>` fixed the issue for me.

**Comment by Kureev** [comment] 2015-10-21 13:01
Ok, I think the subject has been solved.
@holmesal Can you create an issue about styling `Text` element inside `BlurView`? (That would be awesome, if you can attach some code to it)

**Closed by Kureev** 2015-10-21 13:01 UTC
Labels: feedback needed

**Comment by viperfx** [comment] 2016-04-07 16:04
@alvaromb Could you please post a sample of how you achieved a blurred bar with a non blurred image underneath?
